#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Rutas para usuario#
user:
    path: /usuario
    controller: App\Controller\UserController::index

register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]


# Rutas para video#
video:
    path: /video/{id}
    controller: App\Controller\VideoController::video
    methods: [GET]

video_remove:
    path: /video/{id}
    controller: App\Controller\VideoController::remove
    methods: [DELETE]

video_new:
    path: /video/new
    controller: App\Controller\VideoController::newVideo
    methods: [POST]

videos:
    path: /videos
    controller: App\Controller\VideoController::list
    methods: [GET]

video_edit:
    path: /video/edit/{id}
    controller: App\Controller\VideoController::newVideo
    methods: [PUT]